Concert/concert/accounts/urls.py
from django.urls import path
from accounts import views


urlpatterns = [
    path('login/', views.loginView,name="login"),
    path('logout/', views.logoutView),
    path('profile/', views.profileView),
    path('profileRegister', views.profileRegisterView),
    path('profileEdit', views.ProfileEditView),
    path('changepassword',views.changePasswordView,name='change_password'),

]

Concert/concert/accounts/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class ProfileModel(models.Model):
    class Meta:
        verbose_name="کاربر"
        verbose_name_plural="کاربر"

    user=models.OneToOneField(User,on_delete=models.CASCADE,verbose_name="کاربری",related_name="profile")

    # Name=models.CharField(max_length=100,verbose_name="نام")
    # Family=models.CharField(max_length=100,verbose_name="نام خانوادگی")
    ProfileImage=models.ImageField(upload_to="ProfileImages/",verbose_name="عکس")
    
    Man=1
    Woman=2
    status_chioces=((Man,"مرد"),(Woman,"زن"))

    Gender=models.IntegerField(choices=status_chioces,verbose_name="جنسیت")

    Credit=models.IntegerField(verbose_name="اعتبار", default=0)

   

Concert/concert/accounts/forms.py
from django import forms
from django.forms import fields
from accounts.models import ProfileModel
from django.contrib.auth.forms import UserChangeForm
from captcha.fields import CaptchaField

class ProfileRegisterForm(forms.ModelForm):
    first_name = forms.CharField(max_length=100)
    last_name = forms.CharField(max_length=100)
    username = forms.CharField(max_length=100)
    password = forms.CharField(widget=forms.PasswordInput)
    email = forms.CharField(widget=forms.EmailInput)
    captcha = CaptchaField()


    class Meta:
        model=ProfileModel
        fields=['ProfileImage','Credit','Gender']

class ProfileEditForm(forms.ModelForm):
    class Meta:
        model=ProfileModel
        fields=['ProfileImage','Credit','Gender']

class UserEditForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        fields=["first_name","last_name","email"]
    password=None

Concert/concert/accounts/views.py
from django.contrib.auth import authenticate,login,logout
from django.shortcuts import render, redirect
from django.http import HttpResponse,HttpResponseRedirect
import ticketSales
import accounts
from django.urls import reverse
from django.conf import settings
from django.contrib.auth.decorators import login_required
from accounts.forms import ProfileRegisterForm,ProfileEditForm,UserEditForm
from django.contrib.auth.models import User
from accounts.models import ProfileModel
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib import messages



def loginView(request):
    #Post
    if request.method=='POST':
        username=request.POST.get('username')
        password=request.POST.get('password')
        user=authenticate(request,username=username,password=password)

        if user is not None:
            login(request,user)
            if request.GET.get('next'):
                return HttpResponseRedirect(request.GET.get("next"))
                
            return HttpResponseRedirect(settings.LOGIN_REDIRECT_URL)
        else:
            context={
                "username":username,
                "errorMessage":"کاربری با این مشخصات یافت نشد"
            }
            return render(request, "accounts/login.html",context)
     #Get
    else:
        return render(request, "accounts/login.html",{})

def logoutView(request):
    logout(request)
    return HttpResponseRedirect(reverse(ticketSales.views.concertListView))

@login_required
def profileView(request):
    profile=request.user.profile

    context={
        "profile":profile
    }

    return render(request,"accounts/profile.html",context)



def profileRegisterView(request):

    if request.method=="POST":
        profileRegisterForm=ProfileRegisterForm(request.POST,request.FILES)
        if profileRegisterForm.is_valid():

            user = User.objects.create_user(username=profileRegisterForm.cleaned_data["username"],
                                email=profileRegisterForm.cleaned_data['email'],
                                password=profileRegisterForm.cleaned_data['password'],
                                first_name=profileRegisterForm.cleaned_data['first_name'],
                                last_name=profileRegisterForm.cleaned_data['last_name'])

            user.save()

            profileModel=ProfileModel(user=user,
                                       ProfileImage=profileRegisterForm.cleaned_data['ProfileImage'],
                                        Gender=profileRegisterForm.cleaned_data['Gender'],
                                        Credit=profileRegisterForm.cleaned_data['Credit'])

            profileModel.save()

            return HttpResponseRedirect(reverse(ticketSales.views.concertListView))
    else:
        profileRegisterForm=ProfileRegisterForm()

  
    context={
        "formData":profileRegisterForm
    }


    return render(request,"accounts/profileRegister.html",context)


def ProfileEditView(request):
    
    if request.method=="POST":
        profileEditForm=ProfileEditForm(request.POST,request.FILES, instance=request.user.profile)
        userEditForm=UserEditForm(request.POST,instance=request.user)
        if profileEditForm.is_valid and userEditForm.is_valid:
            profileEditForm.save()
            userEditForm.save()
            return HttpResponseRedirect(reverse(accounts.views.profileView))
    else:
        profileEditForm=ProfileEditForm(instance=request.user.profile)
        userEditForm=UserEditForm(instance=request.user)

    context={

        "profileEditForm":profileEditForm,
        "userEditForm":userEditForm,
        "ProfileImage":request.user.profile.ProfileImage,
        
    }

    return render(request,"accounts/profileEdit.html",context)
    
@login_required
def changePasswordView(request):
    
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Your password was successfully updated!')
            return redirect('change_password')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'accounts/changepassword.html', {'form': form})

Concert/concert/accounts/templates/accounts/changepassword.html
{% extends "ticketsales/layout.html" %}

{% block titlepage %}
  تغییر رمز عبور 
{% endblock %}

{% block mainContent %}

  <form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.non_field_errors }}
    <br>
    <div>
    <table>
      <tr>
        <td>رمز قبلی:</td><td>{{form.old_password}}</td>
      </tr>
      <tr>
        <td> رمز جدید:</td><td>{{form.new_password1}}</td>
      </tr>
      <tr>
        <td> تکرار رمز جدید:</td><td>{{form.new_password2}}</td>
      </tr>    
    </table>
  </div><br>
    <div><button type="submit">ذخیره</button></div>
    {% for field in form %}
      <p>{{ field.errors }}</p>
    {% endfor %}
    <ul style="color: red ;">
      <li> Your password can’t be too similar to your other personal information.</li>
      <li> Your password must contain at least 8 characters.</li>
      <li> Your password can’t be a commonly used password.</li>
      <li> Your password can’t be entirely numeric.</li>
    </ul>
    
  </form>

{% endblock %}

Concert/concert/accounts/templates/accounts/profile.html
{% extends "ticketSales/layout.html" %}

{% block titlepage %} 
    پروفایل {{ concertdetails.Name }}
{% endblock%}

{% block mainContent %}
   <div class="row" style="margin-top: 20px;">
      
            <div class="col-md-9">
                <div >
                    <p class="border"> <span class="title">نام و نام خانوادگی: </span> {{ profile.user.get_full_name }} </p>
                    <p class="border"> <span class="title">جنسیت: </span> {{ profile.get_Gender_display }}</p>
                    <p class="border"><span class="title">مقدار اعتبار: </span> {{ profile.Credit }}</p>
                    <ul class="btnul">
                        <li><a class="btn btn-primary" href="/accounts/profileEdit"> ویرایش پروفایل</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md-3" dir="ltr">
                    <img src="{{ profile.ProfileImage.url }}" style="width:100%;height:auto">
            </div>
      
    </div>
{% endblock%}

Concert/concert/accounts/templates/accounts/profileEdit.html
{% extends "ticketSales/layout.html" %}

{% block titlepage %} 
    ویرایش پروفایل
{% endblock%}

{% block mainContent %}

    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
      
        <div class="mainborder">
            <div class="row">
                <div class="col-md-10">
                    <div>
                        <p class="border"> <span class="title">نام: </span>{{userEditForm.first_name}}  </p>
                        <p class="border"> <span class="title"> نام خانوادگی: </span> {{userEditForm.last_name}} </p>
                        <p class="border"> <span class="title">ایمیل: </span> {{userEditForm.email}} </p>
                        <p class="border"> <span class="title">جنسیت: </span> {{ profileEditForm.Gender }}</p>
                        <p class="border"><span class="title">مقدار اعتبار: </span> {{ profileEditForm.Credit }}</p>
                    
                    </div>
                </div>
                <div  class="col-md-2">
                    <div class="imageBox">
                        <img src="{{ ProfileImage.url }}">
                    </div>
                    {{ profileEditForm.ProfileImage }}
                </div>
           </div>
            <div class="bottonborder">
				<a class="btn btn-primary" href="/accounts/changepassword">تغییر رمز عبور</a>
                <button type="submit" class="btn btn-success">ذخیره</button>
            </div>
        </div>
    </form>
{% endblock%}

Concert/concert/accounts/templates/accounts/profileRegister.html
{% extends "ticketSales/layout.html" %}
{% load static %}

{% block titlepage %} 
    فرم ثبت نام 
{% endblock%}

{% block mainContent %}
  
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
      
        <div class="mainborder">
            <div class="row">
                <div class="col-md-6">
                    <p class="mylable">Name: {{ formData.first_name }}</p>
                    <p class="mylable">Family: {{ formData.last_name }}</p>
                    <p class="mylable">Gender: {{ formData.Gender }}</p>
                    <p class="mylable">Credit: {{ formData.Credit }}</p>
                  
                  
                </div>
                <div  class="col-md-6">
                    <p class="mylable">Email: {{ formData.email }}</p>
                    <p class="mylable">UserName: {{ formData.username }}</p>
                    <p class="mylable">Password: {{ formData.password }}</p>
                    <p><a href="" class="captcha-refresh"><img src="{% static 'ticketSales/images/refresh.jpg' %}" alt="Refresh" width="20" height="auto"></a>{{formData.captcha}}</p>
                    {{ formData.ProfileImage }}
                </div>
            </div>
        </div>
        <div class="bottonborder">
            <button type="submit" class="btn btn-success">ثبت نام</button>
        </div>
    </form>
{% endblock%}